services:
  trilium-util:
    image: itecx/trilium-util:latest
    ports:
      - 80:80
    volumes:
      - ./exports:/exports
    environment:
      - TRU_SERVER=null
      - TRU_ETAPI_TOKEN=null
      - TRU_PASSWORD=null
      - TRU_PASSWORDLESS_VIEWING=false
    labels:
      kompose.service.type: nodeport
