---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o trilium-util.k8s.yaml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -o trilium-util.k8s.yaml
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml -o trilium-util.k8s.yaml
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/trilium-util-default: "true"
        io.kompose.service: server
    spec:
      containers:
        - env:
            - name: TRU_ETAPI_TOKEN
              value: TRILIUM ETAPI TOKEN
            - name: TRU_PASSWORD
              value: INTERFACE PASSWORD
            - name: TRU_PASSWORDLESS_VIEWING
              value: "false"
            - name: TRU_SERVER
              value: TRILIUM SYNC SERVER
          image: itecx/trilium-util:latest
          name: server
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /exports
              name: server-claim0
      restartPolicy: Always
      volumes:
        - name: server-claim0
          persistentVolumeClaim:
            claimName: server-claim0
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: server-claim0
  name: server-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: trilium-util-default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/trilium-util-default: "true"
  podSelector:
    matchLabels:
      io.kompose.network/trilium-util-default: "true"

